### get
GET http://192.168.49.2:31930/v1/users/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2EwMDFjYmU1OGViYmZlNzFhMTZmMjAiLCJpYXQiOjE2NzE0MzQ4NTUsImV4cCI6MTY3MTQzNjY1NSwidHlwZSI6ImFjY2VzcyJ9.ZhcSibhmZH3Szu38lsdOarRBh_xEchHyk38_wWcHDck

### create
POST http://localhost:3000/v1/users/
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MzlmNDAyZDUwNWQzOTllZmU2N2VkYzYiLCJpYXQiOjE2NzEzODEwNTQsImV4cCI6MTY3MTM4Mjg1NCwidHlwZSI6ImFjY2VzcyJ9.3CIzwiDCDODDtdf9unGzrRK6ZZ5JC0TZhazpkxvcgoU


{
    "name": "normal user",
    "email": "normal_user@gmail.com",
    "password": "12345678a",
    "role": "user"
}

### update
PATCH http://localhost:3000/v1/users/639dad912f65b6c309d67565/
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MzlmNDAyZDUwNWQzOTllZmU2N2VkYzYiLCJpYXQiOjE2NzEzODEwNTQsImV4cCI6MTY3MTM4Mjg1NCwidHlwZSI6ImFjY2VzcyJ9.3CIzwiDCDODDtdf9unGzrRK6ZZ5JC0TZhazpkxvcgoU

{
    "name": "bagasys3",
    "email": "admin@gmail.com",
    "role": "admin",
    "password": "12345678a"
}

### get by id
GET http://localhost:3000/v1/users/639dad912f65b6c309d67565/
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MzlmM2I0OWNhMTFjYWYxYmNlOGI0MWIiLCJpYXQiOjE2NzEzODA4NzUsImV4cCI6MTY3MTM4MjY3NSwidHlwZSI6ImFjY2VzcyJ9.8w6p0vwd-lz_vjFUAB1TRqldnNyjy3gTqHrgCAmRpsA



### delete
DELETE http://localhost:3000/v1/users/639f3b49ca11caf1bce8b41b/
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MzlmNDAyZDUwNWQzOTllZmU2N2VkYzYiLCJpYXQiOjE2NzEzODEwNTQsImV4cCI6MTY3MTM4Mjg1NCwidHlwZSI6ImFjY2VzcyJ9.3CIzwiDCDODDtdf9unGzrRK6ZZ5JC0TZhazpkxvcgoU


### login
POST http://192.168.49.2:31930/v1/auth/login/
content-type: application/json

{
    "email": "admin1@gmail.com",
    "password": "12345678a"
}

### logout
POST http://localhost:3000/v1/auth/logout/
content-type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MzlkYWQ5MTJmNjViNmMzMDlkNjc1NjUiLCJpYXQiOjE2NzEzNTA4ODUsImV4cCI6MTY3MTQzNzI4NSwidHlwZSI6InJlZnJlc2gifQ.mn4V8tacf2dfIqHvbtVlYxt1mfLVUByFZ3bZku5gW60"
}

### refresh token
POST http://localhost:3000/v1/auth/refresh-token/
content-type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MzlkYWQ5MTJmNjViNmMzMDlkNjc1NjUiLCJpYXQiOjE2NzEzNTA0MjAsImV4cCI6MTY3MTQzNjgyMCwidHlwZSI6InJlZnJlc2gifQ.M-pjSdpD5sWcmkYygTA0rKdqXPvV-5cgyl0Snq4EW4I"
}

### refresh token
POST http://localhost:3000/v1/auth/refresh-token/
content-type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MzlkYWQ5MTJmNjViNmMzMDlkNjc1NjUiLCJpYXQiOjE2NzEzNTA2OTgsImV4cCI6MTY3MTQzNzA5OCwidHlwZSI6InJlZnJlc2gifQ.lRYrvTnyps7ZSdSYfe2XeeyK9A6CrM_--tIpni4uFj4"
}