apiVersion: v1
kind: Service
metadata:
  name: deall
spec:
  selector:
    app: deall
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deall
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deall
  template:
    metadata:
      labels:
        app: deall
    spec:
      containers:
        - name: deall
          image: bagasys/deall:1.0.0
          ports:
            - containerPort: 3000
          env:
            - name: MONGODB_URL
              value: mongodb://mongo:27017/deall
          imagePullPolicy: Always
